from enum import Enum
class Operations(Enum):
    ADD = "ADD"
    SUB = "SUB"
    MUL = "MUL"
    DIV = "DIV"
    SORT = "SORT"
    UNION = "UNION"
    DIFF = "DIFF"
    INTER = "INTER"
    MAP = "MAP"
    REDUCE = "REDUCE"
    STATS = "STATS"
    QUIT = "QUIT"
    HIST = "HIST"
    STOCK = "STOCK"
    PARIS = "PARIS"
    DAYS = "DAYS"
    COUNT = "COUNT"
    WEEK = "WEEK"