name: DevOps

on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Analyzing the code with pylint
      run: |
        python -m pylint --fail-under=10 `find -regextype egrep -regex '(.*.py)$'` |
        tee pylint.txt
    - name: Upload pylint.txt as artifact
      uses: actions/upload-artifact@v2
      with:
        name: pylint report
        path: pylint.txt
    - name: Run python files
      run: |
        python test_demos.py | tee test_demos.txt
    - name: Upload test_demos.txt as artifact
      uses: actions/upload-artifact@v2
      with:
        name: demos output report
        path: test_demos.txt
    - name: Publish 
      shell: pwsh
      run: .\publish_slides.ps1
